# Юнит-2, Разведывательный анализ данных

In [13]:
#9.2.4
import numpy as np
display(np.ones((5,5)))
display(np.eye(5))
display(np.full((5,5), 1))
display(np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]]))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [25]:
#9.2.5
import numpy as np
display(np.random.randint(0, 5, (3, 3)))
display(np.random.randint(0, 6, (3, 3)))

array([[0, 0, 2],
       [2, 3, 4],
       [4, 0, 0]])

array([[3, 4, 0],
       [3, 4, 0],
       [3, 1, 4]])

In [33]:
#9.2.6
import numpy as np
display(np.array([i for i in range(11) if i%2]))
for i in range(11):
    print(i, i%2)
display(np.arange(1, 14, 2))

array([1, 3, 5, 7, 9])

0 0
1 1
2 0
3 1
4 0
5 1
6 0
7 1
8 0
9 1
10 0


array([ 1,  3,  5,  7,  9, 11, 13])

In [49]:
#9.3.1
import numpy as np
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
display(big_secret.shape)
summ = 0
for i in big_secret[:,-1]:
    summ += i
print(round(summ,2))


(5, 51)

3154.33


In [83]:
#9.3.2
import numpy as np
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
display(big_secret.shape)
summ = 0
for i in range(5):
    summ += big_secret[i, i]
print(round(summ,2))

(5, 51)

121.37


In [81]:
#9.3.3
import numpy as np
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
summ = []
for i in range(5):
    summ.append(big_secret[i, i+46])
print(np.prod(summ))

341505315559.2347


In [99]:
#9.3.-
import numpy as np
import time
from datetime import datetime
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

start_time = datetime.now()
for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if (j%2 == 0) and (i%2 == 0):
            big_secret[i, j] = -1
        else:
            big_secret[i, j] = 1
print(datetime.now() - start_time)

start_time = datetime.now()
for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if (i%2 == 0) and (j%2 == 0):
            big_secret[i, j] = -1
        else:
            big_secret[i, j] = 1
print(datetime.now() - start_time)

display(big_secret)

0:00:00
0:00:00


array([[-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,
        -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
         1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 

In [86]:
#9.3.4
import numpy as np
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if (j%2 == 0) and (i%2 == 0):
            big_secret[i, j] = -1
        else:
            big_secret[i, j] = 1

summ = 0
for i in range(5):
    summ += big_secret[i, i]
print(summ)

-1.0


In [93]:
#9.3.5
import numpy as np

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])


for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if (j%2 == 0) and (i%2 == 0):
            big_secret[i, j] = -1
        else:
            big_secret[i, j] = 1

summ = []
for i in range(5):
    summ.append(big_secret[i, i+46])
print(np.prod(summ))


-1.0


In [102]:
#9.4.1
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

display(great_secret.shape[1])

3

In [114]:
#9.4.2
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

display(great_secret[0])
display(round(np.cos(great_secret[0]).sum(),2))

array([ 0.        ,  4.64158883, 66.66666667])

0.16

In [118]:
#9.4.3
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

display(great_secret[great_secret > 50].sum())
#display(round(np.cos(great_secret[0]).sum(),2))

5470.0

In [121]:
#9.4.4
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

display(great_secret.flatten()[150])

7.0710678118654755

In [129]:
#9.4.5
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

display(round(np.sort(great_secret, axis=0)[-1,:].sum(),2))

115.12

In [200]:
#9.5
import numpy as np
table = """1	135	34	4
2	160	43	5
3	163	40	4.3
4	147	44	5
5	138	41	4.7
6	149	54	3.9
7	136	39	4.2
8	154	48	4.9
9	137	35	3.7
10	165	60	4.6"""
students = [list(map(float, l.split('\t'))) for l in table.split('\n')]
students = np.array(students)
display(students)

#9.5.1 Чему равно медианное значение массы тела школьников?
display(np.median(students[:,-2]))

#9.5.2 На сколько среднее арифметическое массы тела школьников больше медианного
#значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.
display(round(np.mean(students[:,-2]) - np.median(students[:,-2]),1))

#9.5.3 Между какой парой признаков в массиве students наблюдается минимальная корреляция?
display(np.round(np.corrcoef(students[:,1], students[:,2]), 2))
display(np.round(np.corrcoef(students[:,1], students[:,3]), 2))
display(np.round(np.corrcoef(students[:,2], students[:,3]), 2))

#9.5.4 Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.
display(np.std(students[:,3]))

#9.5.5 Посчитайте, чему равна дисперсия значений веса школьников.
display(np.std(students[:,2])**2)
display(np.var(students[:,2]))
display(np.mean(students[:,2]))
display(np.min(students[:,2]))
display(np.max(students[:,2]))

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

42.0

1.8

array([[1.  , 0.64],
       [0.64, 1.  ]])

array([[1.  , 0.46],
       [0.46, 1.  ]])

array([[1. , 0.3],
       [0.3, 1. ]])

0.4517742799230607

60.36

60.36

43.8

34.0

60.0

In [184]:
#9.7.3
import numpy as np
np.random.randint(1, 10, (10, 10))

array([[3, 5, 8, 8, 6, 8, 3, 5, 9, 1],
       [9, 5, 3, 4, 5, 6, 6, 4, 5, 1],
       [6, 2, 4, 9, 1, 2, 4, 5, 5, 6],
       [5, 1, 3, 6, 9, 8, 5, 9, 4, 5],
       [9, 4, 6, 9, 5, 4, 5, 7, 1, 3],
       [1, 8, 6, 8, 3, 6, 1, 1, 3, 1],
       [1, 7, 1, 8, 8, 1, 4, 5, 1, 9],
       [1, 2, 8, 9, 9, 5, 1, 7, 7, 6],
       [2, 1, 4, 7, 9, 7, 6, 2, 3, 4],
       [4, 9, 4, 9, 8, 3, 2, 1, 7, 8]])

In [185]:
#9.7.4
import numpy as np
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
display(my_array[1:4,1:4])

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [186]:
#9.7.5
import numpy as np
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
display(round(my_sin.sum(),3))

-0.058

In [187]:
#9.7.6
import numpy as np
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
my_sin[1:4, 1:4] = 1
display(my_sin)
display(round(my_sin.sum(),3))

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

7.572

In [188]:
#9.7.7
import numpy as np
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
my_sin[1:4, 1:4] = 1
display(round(my_sin[:,0:4].reshape((10, 2))[:,0].sum(),3))

2.406

In [205]:
#9.7.8-10
# Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.
import numpy as np
bigdata = np.arange(101, 1000, 2)
bigdata = bigdata ** 2

#9.7.8 Чему равна медиана массива bigdata?
display(np.median(bigdata))

#9.7.9 Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:
display(round(np.std(bigdata)))

#9.7.10 Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами?
#Введите полученный ответ без изменений и округлений.
display(np.corrcoef(bigdata[::2], bigdata[1::2]))


302501.0

292095.0

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])